### ISSUE TITLE
Spinner Offset -> default offset

### ISSUE THREAD

**Issue by IanDCarroll** [DiceHard/n20-android#3]
As a user, I need the option to ignore which side is facing up and just hit the roll button to get a die roll so that I don't have to think, I can still just roll. Whatever the results of the last die roll needs to be the default value of the spinner. If it's the first roll, it is set to a random number on the die.

**Comment by davidlarrimore** [comment]
Hey @IanDCarroll, Please review. Added to commit 269b915

**Comment by IanDCarroll** [comment]
I think I get how you did it. At a glance it looks sound.

I was thinking we might want a test to see if it's really doing it, 
but when we add the display features, that'll be a pretty good indicator.

**Comment by davidlarrimore** [comment]
Probably some debug logging. I can set that up tonight

Thanks,
David Larrimore
