### ISSUE TITLE
Spinner Offset -> user select

### ISSUE THREAD

**Issue by davidlarrimore** [DiceHard/n20-android#4]
As a user, I need a spinner to select which side of the die is facing up when I roll it so that I can add a simple layer of input into the random result and partially determine the fate of the roll.

**Comment by davidlarrimore** [comment]
Hey @IanDCarroll ,

Before I go ahead and do this, there are 2 main options...one is using the "SeekBar" object, which is kind of like a html slider bar....the other option is to setup a gesture control so that when someone "swipes" somewhere on the screen, it will increment the die....I would probably set it up so that the farther someone swipes, the larger the increment. Lets talk tomorrow.

**Comment by IanDCarroll** [comment]
Maybe we can try the easier of the two and see how it looks? 
How difficult would it be to swap it out if we needed to?

Also...
Might be a good UI choice to make the result displayed be what they swipe or slide to alter the value. 
What do you think? 
Big red button on the lower half; big swipey display on the upper half? :bamboo:

**Comment by davidlarrimore** [comment]
The gesture is the better solution in my mind, but the SeekBar will be easier to implement.

**Comment by IanDCarroll** [comment]
Well if gesture is worth the trouble in your opinion then we should go with that

**Comment by IanDCarroll** [comment]
Could you double-check your solution? 
When I updated my device I didn't notice any change in sensitivity.

I'll take a look on my end as well.

**Comment by davidlarrimore** [comment]
Are you switching to the Issue#4 branch?

Thanks,
David Larrimore

**Comment by IanDCarroll** [comment]
Nope! I'll try that and I bet this 'bug' is fixed by that. I AM THE BUG!

**Comment by IanDCarroll** [comment]
I've merged this. It looks to be a good direction to move forward in. May need some future fine-tuning, but this was the work of a warrior. This code is honorable, and will taste the blood of its enemies! **Q'plah!** :hocho: :japanese_ogre: :wine_glass:
