### ISSUE TITLE
One button for rolling

### ISSUE THREAD

**Issue by IanDCarroll** [DiceHard/n20-android#5]
As a user, I want a big red button that's a circle and says "Roll" centered at the bottom half of the screen right where my thumb can get to it. I want to tap it to roll whatever I have selected. That way I don't have to think about the app, I can focus on the fun of playing the game.

**Comment by davidlarrimore** [comment]
Hey Ian, check to see if this is resolved in the commit from Issue #3

**Comment by IanDCarroll** [comment]
Basically right! I'll work on tweaking it to make it more red and circular. How it looks on "el telefono"...
![screenshot_20160721-005834](https://cloud.githubusercontent.com/assets/14797009/17015549/8e0d9f90-4edf-11e6-96b3-a156f8fa813d.png)
![screenshot_20160721-010104](https://cloud.githubusercontent.com/assets/14797009/17015554/9375f1c6-4edf-11e6-9451-0ea687396b3a.png)

**Comment by IanDCarroll** [comment]
![screenshot_20160721-114310](https://cloud.githubusercontent.com/assets/14797009/17034686/9476ba70-4f38-11e6-8178-fb51bba44c63.png)
OK, the colors and shape are there. Still tweakable so that's nice.

Next steps: the textview is centered, but by its left margin. We need it to be truly centered and both when the result is 1 digit or 2 digits.

I'd like a box drawn around the text view that changes shape when we select different die types. And that is also where we can set the die's offset.

But I'm callingredients this done.

**Comment by davidlarrimore** [comment]
Ian, can you create a issue for centering the text ire text?

Thanks,
David Larrimore
